<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yara Ismail">
<meta name="dcterms.date" content="2026-09-22">

<title>Miao et al.&nbsp;2026 – BBB Gene Conservation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-6b38416d90cdbb41281c8a2a0df0236b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">BBB Gene Conservation</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../pipeline.html"> 
<span class="menu-text">Pipeline &amp; Methods</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../results.html"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../audit.html"> 
<span class="menu-text">Audit</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../literature-review.html"> 
<span class="menu-text">Literature</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../glossary.html"> 
<span class="menu-text">Glossary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../data-code.html"> 
<span class="menu-text">Data &amp; Code</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Mmynemious/BBB-Gene-Conservation"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#my-reading" id="toc-my-reading" class="nav-link active" data-scroll-target="#my-reading">My reading</a></li>
  <li><a href="#what-i-take-from-it" id="toc-what-i-take-from-it" class="nav-link" data-scroll-target="#what-i-take-from-it">What I take from it</a></li>
  <li><a href="#checks-against-the-paper" id="toc-checks-against-the-paper" class="nav-link" data-scroll-target="#checks-against-the-paper">Checks against the paper</a></li>
  <li><a href="#the-species-specific-genes-it-names" id="toc-the-species-specific-genes-it-names" class="nav-link" data-scroll-target="#the-species-specific-genes-it-names">The species-specific genes it names</a></li>
  <li><a href="#how-it-relates-to-this-project" id="toc-how-it-relates-to-this-project" class="nav-link" data-scroll-target="#how-it-relates-to-this-project">How it relates to this project</a></li>
  <li><a href="#annotated-scan" id="toc-annotated-scan" class="nav-link" data-scroll-target="#annotated-scan">Annotated scan</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Miao et al.&nbsp;2026</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Distinct gene expression profiles in blood-brain barrier capillary endothelial cells between mice and humans</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yara Ismail </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Miao Y, Wang J, Li W, Mäe MA, Jeansson M, Muhl L, He L (2026). Distinct gene expression profiles in blood-brain barrier capillary endothelial cells between mice and humans. <em>Microvascular Research</em> 166:104933. <a href="https://doi.org/10.1016/j.mvr.2026.104933" class="uri">https://doi.org/10.1016/j.mvr.2026.104933</a>. Open access under CC BY 4.0.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 78%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Year</strong></td>
<td>2026. Received 6 January, accepted 8 March, online 12 March 2026</td>
</tr>
<tr class="even">
<td><strong>Models</strong></td>
<td><strong>Mouse and human</strong>, adult, compared directly. Four datasets across two platforms: mouse Smart-seq and 10x from the authors’ own earlier work, human Allen Brain Atlas snRNA-seq and a 10x scRNA-seq dataset</td>
</tr>
<tr class="odd">
<td><strong>Brain region</strong></td>
<td>Not the focus, and the human tissue is mixed. Human Smart-seq is <strong>post-mortem</strong> brain from three individuals, mean PMI 22.7 h; human 10x is <strong>fresh surgical peritumoral tissue adjacent to gliomas</strong>. Mouse is whole brain vasculature</td>
</tr>
<tr class="even">
<td><strong>Measures</strong></td>
<td><strong>RNA.</strong> Single-cell and single-nucleus transcriptomes, restricted to <strong>capillary</strong> endothelial cells specifically</td>
</tr>
<tr class="odd">
<td><strong>Method</strong></td>
<td>scRNA-seq and snRNA-seq on Smart-seq and 10x. Validated against in situ hybridisation and immunohistochemistry from the Allen Brain Atlas and the Human Protein Atlas</td>
</tr>
<tr class="even">
<td><strong>Cross-species stats</strong></td>
<td><strong>One-to-one orthologous gene pairs only</strong>, from Ensembl, cross-checked against NCBI Gene. 15,675 pairs. Seurat <code>FindMarkers</code> with <strong>Wilcoxon rank-sum</strong>, <strong>Bonferroni-adjusted</strong> <em>P</em> &lt; 0.05. Cell numbers downsampled so the two species are matched. Ribosomal genes excluded</td>
</tr>
</tbody>
</table>
<section id="my-reading" class="level2">
<h2 class="anchored" data-anchor-id="my-reading">My reading</h2>
<p>This was a very fitting paper. At the very beginning they just talk about what they are doing, and their objective was to compare the transcriptomic profile of <strong>blood brain barrier capillary endothelial cells</strong> between adult mice and humans.</p>
<p>What they found is that <strong>169 genes were consistently enriched in human</strong> BBB capillary endothelial cells compared to mouse, whereas <strong>386 genes were enriched in mouse</strong> compared to human. They have some species specific genes that were expressed in just one or the other.</p>
<p>What they conclude is that there is <strong>broad conservation</strong>, but that the distinct transcriptomic differences between human and mouse BBB capillary endothelial cells need to be taken seriously. At the very end they also talk about how this is applicable to the <strong>drug development</strong> process.</p>
<p><strong>Introduction.</strong> First they introduce the function of endothelial cells, and how other people have tried to understand the transcriptomic profile. Turns out that <strong>bulk RNA is limited due to the lack of cellular resolution</strong>. I am not quite sure exactly what they mean here, but maybe it is the missing data. Only with the emergence of <strong>single cell RNA sequencing</strong> and <strong>single nucleus RNA sequencing</strong> have they been able to do a much more precise characterisation of barrier cell types.</p>
<p><strong>Materials and methods.</strong> Specifically I had to look out for what method they were using: are they referring to single nucleus RNA sequencing or single cell RNA sequencing. These were things I needed to watch for.</p>
<p>They also talk about their <strong>manual inspection</strong> to remove a small number of contaminating cells. They removed cells with <strong>pericyte marker expression</strong>, and also <strong>immune cell markers</strong>.</p>
<p>Then they looked at the human snRNA-seq and scRNA-seq data. They talk about their patient age and so on.</p>
<p><strong>Data integration and comparison</strong> is pretty solid, because we did something similar. They used <strong>one-to-one orthologous gene pairs</strong>. They used <strong>R with the Seurat package</strong>, which we also used. Then they applied the <strong>Wilcoxon rank-sum test</strong>, which we also used, and a <strong>Bonferroni adjusted p-value</strong>, which we also used.</p>
<p><strong>Results.</strong> They again talk about having analysed the transcriptomic profile of mouse and human. It turns out that specifically the markers <strong>CLDN5 and FLT1</strong> were the most abundantly expressed transcripts. They also look at novel markers such as <strong>MFSD2A, KDR and TFRC</strong>, and they find the gene abundance profiles were highly correlated across platforms.</p>
<p>Then they look at the human BBB endothelial transcriptome again, and check that the canonical markers of capillary endothelial cells were consistently recovered in both datasets, which makes their case pretty strong.</p>
<p>Then they looked at the mouse and human BBB endothelial transcriptomes together. They checked the markers, saw that both were expressed in both datasets, and that is when they showed the <strong>species specific enrichment</strong>.</p>
<p>Then they point out that the <strong>SLC transporter family</strong> was specifically expressed, in that a substantial number of the differentially expressed genes belong to this family.</p>
<p>Then they talk about the <strong>validation</strong>, which they did using <strong>ISH images and immunohistochemistry</strong>.</p>
<p><strong>Discussion.</strong> They discuss that the transcriptomic profile has some similarities but is not fully defined, and that when you do drug development you need to watch out specifically for the different enriched genes in the BBB capillary endothelial cell profile between mouse and human.</p>
</section>
<section id="what-i-take-from-it" class="level2">
<h2 class="anchored" data-anchor-id="what-i-take-from-it">What I take from it</h2>
<p>They used the same comparison machinery we did: one-to-one orthologues, Seurat, Wilcoxon, Bonferroni. Seeing our own choices turn up in a 2026 paper in the field is reassuring about the statistics, whatever else is wrong upstream.</p>
</section>
<section id="checks-against-the-paper" class="level2">
<h2 class="anchored" data-anchor-id="checks-against-the-paper">Checks against the paper</h2>
<ul>
<li><strong>On bulk RNA and cellular resolution.</strong> Bulk RNA-seq grinds up the whole tissue and measures the average across every cell in it. Brain tissue is overwhelmingly neurons and glia, so the endothelial signal is a small fraction of the total and cannot be separated out. It is not missing data so much as <strong>blended</strong> data. Single cell and single nucleus methods measure one cell at a time, so capillary endothelial cells can be picked out and compared directly. This is the same problem noted for Wälchli in <a href="../papers/kumabe2025.html">Kumabe</a>.</li>
<li><strong>Both methods are used, on both species.</strong> Mouse is scRNA-seq on two platforms. Human is one <strong>snRNA-seq</strong> dataset (Allen Brain Atlas, Smart-seq) and one <strong>scRNA-seq</strong> dataset (10x).</li>
<li><strong>The human tissue is worth noting.</strong> The post-mortem dataset is three individuals, mean age 49, mean post-mortem interval 22.7 h, yielding only <strong>51</strong> capillary endothelial cells. The surgical dataset is <strong>peritumoral tissue adjacent to gliomas</strong> from seven patients. Neither is healthy brain in the way the mouse tissue is, which is a real limit on the comparison and one the paper does not dwell on.</li>
<li><strong>A small internal inconsistency.</strong> The abstract and results say <strong>386</strong> genes enriched in mouse; the discussion says <strong>385</strong>. Worth knowing which to quote.</li>
<li><strong>The numbers behind the claim.</strong> Cross-platform correlation within mouse was Pearson <em>r</em> = 0.941. Between species the correlation was <em>r</em> = 0.68. 15,675 one-to-one orthologous pairs went into the comparison.</li>
</ul>
</section>
<section id="the-species-specific-genes-it-names" class="level2">
<h2 class="anchored" data-anchor-id="the-species-specific-genes-it-names">The species-specific genes it names</h2>
<p><strong>Higher or specific in mouse:</strong> <code>Slco1c1</code>, <code>Slc22a8</code>, <code>Pglyrp1</code>, <code>Tspan13</code>, <code>Ucp2</code>. <code>Slco1c1</code> encodes Oatp1c1, which carries thyroid hormone T4 across the mouse barrier.</p>
<p><strong>Higher or specific in human:</strong> <code>A2M</code>, <code>CLEC3B</code>, <code>BTNL9</code>, <code>SPOCK3</code>, <code>RUNDC3B</code>. <code>A2M</code> is alpha-2-macroglobulin, a protease inhibitor implicated in amyloid-beta clearance.</p>
<p><strong>Conserved and robust in both:</strong> <code>FLT1</code>, <code>CLDN5</code>, <code>PECAM1</code>, <code>SLC2A1</code> (GLUT1), with <code>MFSD2A</code> and <code>CLDN5</code> consistently recovered as canonical capillary markers.</p>
</section>
<section id="how-it-relates-to-this-project" class="level2">
<h2 class="anchored" data-anchor-id="how-it-relates-to-this-project">How it relates to this project</h2>
<ol type="1">
<li><p><strong>This is the closest paper yet to what the project is doing, and it is two months old.</strong> Same two species, same question of how far mouse stands in for human at the barrier, and published while this project was running. The difference is the measurement: they compare <strong>expression</strong>, this project compares <strong>coding sequence</strong>. That is a real distinction and it is worth stating in the project’s framing rather than discovering later.</p></li>
<li><p><strong>It validates the statistical choices.</strong> One-to-one orthologues, Seurat, Wilcoxon rank-sum, Bonferroni adjustment. That is the same framework as <code>step5e</code> and <code>step5g</code>. The <a href="../audit.html">audit</a> already found the statistics to be the clean part of the pipeline; this is independent confirmation that they match current practice in the field.</p></li>
<li><p><strong>It settles the one-to-many orthologue question.</strong> They restricted to <strong>one-to-one orthologous pairs only</strong>, 15,675 of them, and cross-checked Ensembl against NCBI. This project admitted 196 one-to-many pairs at 25.8% identity into the BBB set in <code>step3b</code>, and then <code>step5d</code> excluded them from the control but not from the BBB set. The field standard is to use one-to-one throughout. That is direct support for the <code>step5d</code> fix.</p></li>
<li><p><strong>The sharpest finding for this project: the divergent family is the SLC family.</strong> A substantial proportion of the differentially expressed genes are solute carriers. This project’s gene list is heavy with SLC transporters, and it is measuring how conserved their <em>sequence</em> is. Miao shows that this is exactly the family whose <em>expression</em> diverges most between mouse and human. So the two measurements may well disagree, with a gene conserved in sequence and expressed quite differently. That is not a problem with either study. It is the most interesting thing either could say, and it is a result this project is positioned to contribute to.</p></li>
<li><p><strong>CLDN5 for the fourth time.</strong> Here it is one of the two most abundantly expressed transcripts in mouse BBB capillary endothelial cells, and a canonical marker robustly expressed in both species. It is still absent from this project’s gene list because it failed an enrichment cutoff. Four independent papers now treat it as central. This needs writing into the <a href="../results.html">limitations</a>.</p></li>
<li><p><strong>It gives a ready-made comparison set.</strong> The 169 human-enriched and 386 mouse-enriched genes are a published, thresholded list of where the two species differ at the barrier. Once this project’s conservation scores are corrected, asking whether those divergent genes are also less conserved in sequence is a direct, cheap and genuinely novel question.</p></li>
</ol>
</section>
<section id="annotated-scan" class="level2">
<h2 class="anchored" data-anchor-id="annotated-scan">Annotated scan</h2>
<div class="scan-note">
<p>My own printed and annotated pages, scanned back in.</p>
</div>
<div class="scan-gallery">
  <figure class="figure">
    <img src="scans/miao2026/p-01.jpg" alt="Annotated page 1 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 1</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-02.jpg" alt="Annotated page 2 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 2</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-03.jpg" alt="Annotated page 3 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 3</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-04.jpg" alt="Annotated page 4 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 4</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-05.jpg" alt="Annotated page 5 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 5</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-06.jpg" alt="Annotated page 6 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 6</figcaption>
  </figure>
  <figure class="figure">
    <img src="scans/miao2026/p-07.jpg" alt="Annotated page 7 of the paper" loading="lazy" class="figure-img">
    <figcaption>Page 7</figcaption>
  </figure>
</div>
<div class="scan-note">
<p>Pages reproduced from Miao et al.&nbsp;2026, <em>Microvascular Research</em> 166:104933, open access under CC BY 4.0. Handwriting and highlighting are mine. <a href="https://doi.org/10.1016/j.mvr.2026.104933">Original paper</a>.</p>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/bbb-gene-conservation\.vercel\.app");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Miao et al. 2026"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Distinct gene expression profiles in blood-brain barrier capillary endothelial cells between mice and humans"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Miao Y, Wang J, Li W, Mäe MA, Jeansson M, Muhl L, He L (2026). Distinct gene expression</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; profiles in blood-brain barrier capillary endothelial cells between mice and humans.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *Microvascular Research* 166:104933. </span><span class="ot">&lt;https://doi.org/10.1016/j.mvr.2026.104933&gt;</span><span class="at">.</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Open access under CC BY 4.0.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Field <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Year** <span class="pp">|</span> 2026. Received 6 January, accepted 8 March, online 12 March 2026 <span class="pp">|</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Models** | **Mouse and human**, adult, compared directly. Four datasets across two platforms: mouse Smart-seq and 10x from the authors' own earlier work, human Allen Brain Atlas snRNA-seq and a 10x scRNA-seq dataset <span class="pp">|</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Brain region** | Not the focus, and the human tissue is mixed. Human Smart-seq is **post-mortem** brain from three individuals, mean PMI 22.7 h; human 10x is **fresh surgical peritumoral tissue adjacent to gliomas**. Mouse is whole brain vasculature <span class="pp">|</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Measures** | **RNA.** Single-cell and single-nucleus transcriptomes, restricted to **capillary** endothelial cells specifically <span class="pp">|</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Method** <span class="pp">|</span> scRNA-seq and snRNA-seq on Smart-seq and 10x. Validated against in situ hybridisation and immunohistochemistry from the Allen Brain Atlas and the Human Protein Atlas <span class="pp">|</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Cross-species stats** | **One-to-one orthologous gene pairs only**, from Ensembl, cross-checked against NCBI Gene. 15,675 pairs. Seurat `FindMarkers` with **Wilcoxon rank-sum**, **Bonferroni-adjusted** *P* &lt; 0.05. Cell numbers downsampled so the two species are matched. Ribosomal genes excluded <span class="pp">|</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>: {tbl-colwidths="<span class="co">[</span><span class="ot">22,78</span><span class="co">]</span>"}</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">## My reading</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>This was a very fitting paper. At the very beginning they just talk about what they are doing,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>and their objective was to compare the transcriptomic profile of **blood brain barrier</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>capillary endothelial cells** between adult mice and humans.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>What they found is that **169 genes were consistently enriched in human** BBB capillary</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>endothelial cells compared to mouse, whereas **386 genes were enriched in mouse** compared to</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>human. They have some species specific genes that were expressed in just one or the other.</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>What they conclude is that there is **broad conservation**, but that the distinct</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>transcriptomic differences between human and mouse BBB capillary endothelial cells need to be</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>taken seriously. At the very end they also talk about how this is applicable to the **drug</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>development** process.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>**Introduction.** First they introduce the function of endothelial cells, and how other people</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>have tried to understand the transcriptomic profile. Turns out that **bulk RNA is limited due</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>to the lack of cellular resolution**. I am not quite sure exactly what they mean here, but</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>maybe it is the missing data. Only with the emergence of **single cell RNA sequencing** and</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>**single nucleus RNA sequencing** have they been able to do a much more precise</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>characterisation of barrier cell types.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>**Materials and methods.** Specifically I had to look out for what method they were using: are</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>they referring to single nucleus RNA sequencing or single cell RNA sequencing. These were</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>things I needed to watch for.</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>They also talk about their **manual inspection** to remove a small number of contaminating</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>cells. They removed cells with **pericyte marker expression**, and also **immune cell</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>markers**.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>Then they looked at the human snRNA-seq and scRNA-seq data. They talk about their patient age</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>and so on.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>**Data integration and comparison** is pretty solid, because we did something similar. They</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>used **one-to-one orthologous gene pairs**. They used **R with the Seurat package**, which we</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>also used. Then they applied the **Wilcoxon rank-sum test**, which we also used, and a</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>**Bonferroni adjusted p-value**, which we also used.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>**Results.** They again talk about having analysed the transcriptomic profile of mouse and</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>human. It turns out that specifically the markers **CLDN5 and FLT1** were the most abundantly</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>expressed transcripts. They also look at novel markers such as **MFSD2A, KDR and TFRC**, and</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>they find the gene abundance profiles were highly correlated across platforms.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>Then they look at the human BBB endothelial transcriptome again, and check that the canonical</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>markers of capillary endothelial cells were consistently recovered in both datasets, which</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>makes their case pretty strong.</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>Then they looked at the mouse and human BBB endothelial transcriptomes together. They checked</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>the markers, saw that both were expressed in both datasets, and that is when they showed the</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>**species specific enrichment**.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>Then they point out that the **SLC transporter family** was specifically expressed, in that a</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>substantial number of the differentially expressed genes belong to this family.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>Then they talk about the **validation**, which they did using **ISH images and</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>immunohistochemistry**.</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>**Discussion.** They discuss that the transcriptomic profile has some similarities but is not</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>fully defined, and that when you do drug development you need to watch out specifically for</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>the different enriched genes in the BBB capillary endothelial cell profile between mouse and</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>human.</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## What I take from it</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>They used the same comparison machinery we did: one-to-one orthologues, Seurat, Wilcoxon,</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>Bonferroni. Seeing our own choices turn up in a 2026 paper in the field is reassuring about</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>the statistics, whatever else is wrong upstream.</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a><span class="fu">## Checks against the paper</span></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**On bulk RNA and cellular resolution.** Bulk RNA-seq grinds up the whole tissue and measures</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>  the average across every cell in it. Brain tissue is overwhelmingly neurons and glia, so the</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>  endothelial signal is a small fraction of the total and cannot be separated out. It is not</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>  missing data so much as **blended** data. Single cell and single nucleus methods measure one</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>  cell at a time, so capillary endothelial cells can be picked out and compared directly. This</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>  is the same problem noted for Wälchli in <span class="co">[</span><span class="ot">Kumabe</span><span class="co">](kumabe2025.qmd)</span>.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Both methods are used, on both species.** Mouse is scRNA-seq on two platforms. Human is one</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>  **snRNA-seq** dataset (Allen Brain Atlas, Smart-seq) and one **scRNA-seq** dataset (10x).</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The human tissue is worth noting.** The post-mortem dataset is three individuals, mean age</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>  49, mean post-mortem interval 22.7 h, yielding only **51** capillary endothelial cells. The</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>  surgical dataset is **peritumoral tissue adjacent to gliomas** from seven patients. Neither is</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>  healthy brain in the way the mouse tissue is, which is a real limit on the comparison and one</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>  the paper does not dwell on.</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**A small internal inconsistency.** The abstract and results say **386** genes enriched in</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>  mouse; the discussion says **385**. Worth knowing which to quote.</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**The numbers behind the claim.** Cross-platform correlation within mouse was Pearson</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>  *r* = 0.941. Between species the correlation was *r* = 0.68. 15,675 one-to-one orthologous</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>  pairs went into the comparison.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a><span class="fu">## The species-specific genes it names</span></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>**Higher or specific in mouse:** <span class="in">`Slco1c1`</span>, <span class="in">`Slc22a8`</span>, <span class="in">`Pglyrp1`</span>, <span class="in">`Tspan13`</span>, <span class="in">`Ucp2`</span>.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="in">`Slco1c1`</span> encodes Oatp1c1, which carries thyroid hormone T4 across the mouse barrier.</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>**Higher or specific in human:** <span class="in">`A2M`</span>, <span class="in">`CLEC3B`</span>, <span class="in">`BTNL9`</span>, <span class="in">`SPOCK3`</span>, <span class="in">`RUNDC3B`</span>. <span class="in">`A2M`</span> is</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>alpha-2-macroglobulin, a protease inhibitor implicated in amyloid-beta clearance.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>**Conserved and robust in both:** <span class="in">`FLT1`</span>, <span class="in">`CLDN5`</span>, <span class="in">`PECAM1`</span>, <span class="in">`SLC2A1`</span> (GLUT1), with <span class="in">`MFSD2A`</span></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>and <span class="in">`CLDN5`</span> consistently recovered as canonical capillary markers.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a><span class="fu">## How it relates to this project</span></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**This is the closest paper yet to what the project is doing, and it is two months old.**</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>   Same two species, same question of how far mouse stands in for human at the barrier, and</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>   published while this project was running. The difference is the measurement: they compare</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>   **expression**, this project compares **coding sequence**. That is a real distinction and it</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>   is worth stating in the project's framing rather than discovering later.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**It validates the statistical choices.** One-to-one orthologues, Seurat, Wilcoxon</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>   rank-sum, Bonferroni adjustment. That is the same framework as <span class="in">`step5e`</span> and <span class="in">`step5g`</span>. The</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>   <span class="co">[</span><span class="ot">audit</span><span class="co">](../audit.qmd)</span> already found the statistics to be the clean part of the pipeline;</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>   this is independent confirmation that they match current practice in the field.</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**It settles the one-to-many orthologue question.** They restricted to **one-to-one</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>   orthologous pairs only**, 15,675 of them, and cross-checked Ensembl against NCBI. This</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>   project admitted 196 one-to-many pairs at 25.8% identity into the BBB set in <span class="in">`step3b`</span>, and</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>   then <span class="in">`step5d`</span> excluded them from the control but not from the BBB set. The field standard is</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>   to use one-to-one throughout. That is direct support for the <span class="in">`step5d`</span> fix.</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**The sharpest finding for this project: the divergent family is the SLC family.** A</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>   substantial proportion of the differentially expressed genes are solute carriers. This</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>   project's gene list is heavy with SLC transporters, and it is measuring how conserved their</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>   *sequence* is. Miao shows that this is exactly the family whose *expression* diverges most</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>   between mouse and human. So the two measurements may well disagree, with a gene conserved in</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>   sequence and expressed quite differently. That is not a problem with either study. It is the</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>   most interesting thing either could say, and it is a result this project is positioned to</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>   contribute to.</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**CLDN5 for the fourth time.** Here it is one of the two most abundantly expressed</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>   transcripts in mouse BBB capillary endothelial cells, and a canonical marker robustly</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>   expressed in both species. It is still absent from this project's gene list because it</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>   failed an enrichment cutoff. Four independent papers now treat it as central. This needs</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>   writing into the <span class="co">[</span><span class="ot">limitations</span><span class="co">](../results.qmd)</span>.</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**It gives a ready-made comparison set.** The 169 human-enriched and 386 mouse-enriched</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>   genes are a published, thresholded list of where the two species differ at the barrier. Once</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>   this project's conservation scores are corrected, asking whether those divergent genes are</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>   also less conserved in sequence is a direct, cheap and genuinely novel question.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="fu">## Annotated scan</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>::: {.scan-note}</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>My own printed and annotated pages, scanned back in.</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;div class="scan-gallery"&gt;</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-01.jpg" alt="Annotated page 1 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 1&lt;/figcaption&gt;</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-02.jpg" alt="Annotated page 2 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 2&lt;/figcaption&gt;</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-03.jpg" alt="Annotated page 3 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 3&lt;/figcaption&gt;</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-04.jpg" alt="Annotated page 4 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 4&lt;/figcaption&gt;</span></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-05.jpg" alt="Annotated page 5 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 5&lt;/figcaption&gt;</span></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-06.jpg" alt="Annotated page 6 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 6&lt;/figcaption&gt;</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;figure&gt;</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;img src="scans/miao2026/p-07.jpg" alt="Annotated page 7 of the paper" loading="lazy"&gt;</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="in">    &lt;figcaption&gt;Page 7&lt;/figcaption&gt;</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a><span class="in">  &lt;/figure&gt;</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;/div&gt;</span></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>::: {.scan-note}</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>Pages reproduced from Miao et al. 2026, *Microvascular Research* 166:104933,</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>open access under CC BY 4.0. Handwriting and highlighting are mine.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Original paper</span><span class="co">](https://doi.org/10.1016/j.mvr.2026.104933)</span>.</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>:::</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Yara Ismail · Clelland Lab</p>
</div>   
    <div class="nav-footer-center">
<p>Built with Quarto and R</p>
</div>
    <div class="nav-footer-right">
<p><a href="https://github.com/Mmynemious/BBB-Gene-Conservation">Repository</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>